import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-renewable-energy-certificate-settlement",
  "engine": "recovery",
  "title": "Renewable Energy Certificate Settlement",
  "shortTitle": "Renewable Energy Certificate Settlement",
  "tagline": "Reconcile renewable certificate creation, delivery, pricing, retirement, and cash settlement across registries and contracts.",
  "industry": "Environmental Commodity Finance",
  "buyer": "Renewable generators, utilities, and energy traders",
  "uiPort": 4720,
  "apiPort": 5720,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Renewable Energy Certificate Settlement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash in one accountable workflow. Reconcile renewable certificate creation, delivery, pricing, retirement, and cash settlement across registries and contracts.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Renewable Energy Certificate Settlement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("rec-contract-library","REC01","REC contract library","Execute rec contract library using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed rec contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","REC contract library Reference","text","REC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("asset-eligibility-registry","REC02","Asset eligibility registry","Execute asset eligibility registry using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed asset eligibility registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Asset eligibility registry Reference","text","REC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("meter-production-ingestion","REC03","Meter production ingestion","Execute meter production ingestion using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed meter production ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Meter production ingestion Reference","text","REC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("certificate-issuance-matching","REC04","Certificate issuance matching","Execute certificate issuance matching using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed certificate issuance matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Certificate issuance matching Reference","text","REC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("vintage-validation","REC05","Vintage validation","Execute vintage validation using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed vintage validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Vintage validation Reference","text","REC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("product-class-mapping","REC06","Product class mapping","Execute product class mapping using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed product class mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Product class mapping Reference","text","REC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("delivery-schedule-control","REC07","Delivery schedule control","Execute delivery schedule control using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed delivery schedule control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Delivery schedule control Reference","text","REC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("market-price-calculation","REC08","Market price calculation","Execute market price calculation using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed market price calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Market price calculation Reference","text","REC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("transfer-confirmation","REC09","Transfer confirmation","Execute transfer confirmation using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed transfer confirmation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Transfer confirmation Reference","text","REC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("retirement-evidence","REC10","Retirement evidence","Execute retirement evidence using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed retirement evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Retirement evidence Reference","text","REC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("shortfall-penalty-calculation","REC11","Shortfall penalty calculation","Execute shortfall penalty calculation using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed shortfall penalty calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Shortfall penalty calculation Reference","text","REC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("invoice-settlement-matching","REC12","Invoice settlement matching","Execute invoice settlement matching using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed invoice settlement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Invoice settlement matching Reference","text","REC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("registry-dispute-workflow","REC13","Registry dispute workflow","Execute registry dispute workflow using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed registry dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Registry dispute workflow Reference","text","REC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("cash-reconciliation","REC14","Cash reconciliation","Execute cash reconciliation using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Cash reconciliation Reference","text","REC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]}),
feature("asset-market-analytics","REC15","Asset market analytics","Execute asset market analytics using REC contracts, asset eligibility, meter production, registry issuances, vintages, retirements, market prices, transfers, invoices, and cash.","Produce a governed asset market analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Registry / Generation Asset","text","Registry / Generation Asset · Standard Case"],["caseReference","Asset market analytics Reference","text","REC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1566250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1895163],["domainDriver","Certificate Class","select","Compliance REC",["Compliance REC","Voluntary REC","Solar REC"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["REC contract library case","Asset eligibility registry case","Meter production ingestion case","Certificate issuance matching case","Vintage validation case"]})
]);
